services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: pokegentrade-db
    env_file:
      - ./database/.env
    ports:
      - "5420:5432"
    volumes:
      - pokegentrade_db_data:/var/lib/postgresql/18

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bookstore-api
    env_file:
      - .env
    ports:
      - "8020:8000"
    depends_on:
      - db


volumes:
  pokegentrade_db_data: